[package]
name = "civilizations_visualization"
version = "0.1.0"
edition = "2024"

[dependencies]
noise = "0.9"
gl = "0.6.0"
sdl3 = { version = "0.16.1", features = ["build-from-source-static"] }
rand = "0.9.2"
